# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HcQZzoANLr2Nx2mhj2k78fN3DE2eSR23
"""

peso = 16
altura = 6.5
nome = 'gaby'
aluno = False
professor = True

result = peso/altura**2

altura

type(peso)

type(altura)

type(nome)

type(professor)

2 + 3

'ab' + 'cd'

'7' + '8'

type(aluno)

534+862

'Ga' + 'by'

soma = 7+8
print(soma)

soma = 45+ 97
print(soma)

soma = 5+3
print(soma)
subtraçao = 5-3
print(subtraçao)

potencia = 5**3
print(potencia)
multiplicaçao = 5*3
print(multiplicaçao)
resto = 5%3
print(resto)

results = 100*1.1**7
print(results)